### ISSUE TITLE
'Add TomTom waypoint' not working

### ISSUE THREAD

**Issue by Eviloverlord1989** [syndenbock/Handynotes_Pandaria#1]
Using the rightclick menu on the world map gives the error below. Sorry if this isn't caused by your addon.

12x ...ndynotes_Pandaria/modules/handynotes_integration.lua:191: attempt to index local 'info' (a nil value)
[string "@Handynotes_Pandaria/modules/handynotes_integration.lua"]:191: in function `func'
[string "@Blizzard_SharedXML/Mainline/UIDropDownMenu.lua"]:1019: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:133_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:133_OnClick"]:1>

Locals:
button = DropDownList1Button2 {
 0 = <userdata>
 Highlight = DropDownList1Button2Highlight {
 }
 notCheckable = true
 func = <function> defined @Handynotes_Pandaria/modules/handynotes_integration.lua:183
 invisibleButton = DropDownList1Button2InvisibleButton {
 }
 arg2 = 73602360
 NewFeature = Frame {
 }
 hookedfix = true
 arg1 = 422
 value = "Add TomTom waypoint"
 Icon = DropDownList1Button2Icon {
 }
}
mapId = 422
coords = 73602360
x = 0.736000
y = 0.236000
info = nil
(*temporary) = <function> defined @AllTheThings/AllTheThings.lua:4735
(*temporary) = <table> {
 ProjectIsClassic = <function> defined @TomTom/AddonCore.lua:97
 ShowHideCrazyArrow = <function> defined @TomTom/TomTom_CrazyArrow.lua:273
 TEXTURE = "Interface\ChatFrame\ChatFrameBackground"
 Defer = <function> defined @TomTom/AddonCore.lua:357
 GetDirectionToWaypoint = <function> defined @TomTom/TomTom_Waypoints.lua:275
 ResetWaypointOptions = <function> defined @TomTom/TomTom.lua:291
 DebugCoordBlock = <function> defined @TomTom/TomTom.lua:402
 DebugListLocalWaypoints = <function> defined @TomTom/TomTom.lua:1155
 tooltip = TomTomTooltip {
 }
 worldMapClickHandler = TomTomWorldMapClickHandler {
 }
 ClearWaypoint = <function> defined @TomTom/TomTom_Waypoints.lua:242
 slashCommandUsage = <function> defined @TomTom/TomTom.lua:1191
 RegisterModule = <function> defined @TomTom/AddonCore.lua:229
 UpdateCoordFeedThrottle = <function> defined @TomTom/TomTom.lua:351
 DebugListAllWaypoints = <function> defined @TomTom/TomTom.lua:1173
 RegisterMessage = <function> defined @TomTom/AddonCore.lua:317
 ShowHideWorldCoords = <function> defined @TomTom/TomTom.lua:355
 dropdown_uid = <table> {
 }
 GetCurrentCoords = <function> defined @TomTom/TomTom.lua:268
 worlddropdown = TomTomWorldMapDropdown {
 }
 db = <table> {
 }
 GetCZWFromMapID = <function> defined @TomTom/TomTom.lua:1240
 eventFrame = TomTomEventFrame {
 }
 SetCrazyArrowDirection = <function> defined @TomTom/TomTom_CrazyArrow.lua:587
 CreateConfigPanels = <function> defined @TomTom/TomTom_Config.lua:929
 RegisterEvent = <function> defined @TomTom/AddonCore.lua:139
 WOW_CLASSIC = false
 waypoints = <table> {
 }
 UIDIsSaved = <function> defined @TomTom/TomTom.lua:740
 DebugCrazyArrow = <function> defined @TomTom/TomTom_CrazyArrow.lua:628
 SetCrazyArrowTitle = <function> defined @TomTom/TomTom_CrazyArrow.lua:603
 Enable = <function> defined @TomTom/TomTom.lua:213
 waypointprofile = <table> {
 }
 version = "v3.6.2-release"
 CreateWorldMapClickHandler = <function> defined @TomTom/TomTom.lua:512
 ClearAllWaypoints = <function> defined @TomTom/TomTom.lua:282
 RegisterLocale = <function> defined @TomTom/AddonCore.lua:399
 waydb = <table> {
 }
 GetClosestWaypoint = <function> defined @TomTom/TomTom.lua:1275
 defaults = <table> {
 }
 EnableDisablePOIIntegration = <function> defined @TomTom/TomTom_POIIntegration.lua:284
 SetCustomWaypoint = <function> defined @TomTom/TomTom.lua:1048
 AddWaypointToCurrentZone = <function> defined @TomTom/TomTom.lua:893
 CrazyArrowIsHijacked = <function> defined @TomTom/TomTom_CrazyArrow.lua:623
 DefaultCallbacks = <function> defined @TomTom/TomTom.lua:913
 CHAT_MSG_ADDON = <function> defined @TomTom/TomTom.lua:762
 IsDragonflight = <function> defined @TomTom/AddonCore.lua:109
 ReleaseCrazyArrow = <function> defined @TomTom/TomTom_CrazyArrow.lua:617
 WOW_BURNING_CRUSADE_CLASSIC = false
 AddWaypoint = <function> defined @AllTheThings/AllTheThings.lua:4735
 HijackCr

**Comment by syndenbock** [comment]
Thanks for reporting this, this should be fixed in version 1.7.1
