### ISSUE TITLE
[1.7.1 Issue] Right Click on the World Map Forces “Add Handy Note”, Thus Cannot Zoom Out the Current Zone	

### ISSUE THREAD

**Issue by FlareStarrr** [syndenbock/Handynotes_Pandaria#2]
I want to zoom out of the current zone, but ver 1.7.1 forces "Add Handy Note" on the map right click. Reverting to ver 1.7 fixes the issue.

**Comment by syndenbock** [comment]
I just tried reproducing this issue, but I can go to parent zones by right clicking without an issue. To make the "Add Handy Note" box show up I need to hold down the alt key while right clicking. Is it possible that your alt key was stuck or something like that while you tried zooming out?

**Comment by FlareStarrr** [comment]
You're right, my alt key must be stuck before, since both versions of Handynotes work fine now.

The alt key stuck issue did occasionally happen to me before, making me accidentally turning off UI in combat. I didn't think of it since reverting the addon update coincidentally fixed the alt key issue.

**Comment by FlareStarrr** [comment]
You're right, my alt key must be stuck before, since both versions of Handynotes work fine now.

The alt key stuck issue did occasionally happen to me before, making me accidentally turning off UI in combat. I didn't think of it since reverting the addon update coincidentally fixed the alt key issue.

**Comment by syndenbock** [comment]
Yeah I think modifier keys getting stuck is actually an issue with the game itself not the keyboard so I guess when you rolled back the addon you did a reload of course with fixed the issue in the game itself.
